// <auto-generated />
using System;
using KhaiKang.Modules.ProjectManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KhaiKang.Modules.ProjectManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectManagementDbContext))]
    partial class ProjectManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_account_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletionSummary")
                        .HasColumnType("text")
                        .HasColumnName("completion_summary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("DefinitionOfDone")
                        .HasColumnType("text")
                        .HasColumnName("definition_of_done");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("IssueNo")
                        .HasColumnType("integer")
                        .HasColumnName("issue_no");

                    b.Property<Guid>("IssuePriorityId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_priority_id");

                    b.Property<Guid>("IssueStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_status_id");

                    b.Property<Guid>("IssueTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_type_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("ReporterAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_account_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<string>("UserStory")
                        .HasColumnType("text")
                        .HasColumnName("user_story");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("AssigneeAccountId")
                        .HasDatabaseName("idx_issues_assignee_account_id");

                    b.HasIndex("IssuePriorityId")
                        .HasDatabaseName("idx_issues_issue_priority_id");

                    b.HasIndex("IssueStatusId")
                        .HasDatabaseName("idx_issues_issue_status_id");

                    b.HasIndex("IssueTypeId")
                        .HasDatabaseName("idx_issues_issue_type_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_issues_project_id");

                    b.HasIndex("ReporterAccountId")
                        .HasDatabaseName("idx_issues_reporter_account_id");

                    b.HasIndex("ProjectId", "AssigneeAccountId")
                        .HasDatabaseName("idx_issues_project_assignee");

                    b.HasIndex("ProjectId", "IssueNo")
                        .IsUnique()
                        .HasDatabaseName("uq_issues_project_issue_no");

                    b.HasIndex("ProjectId", "IssueStatusId")
                        .HasDatabaseName("idx_issues_project_status");

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.IssueAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("storage_provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<Guid>("UploadedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_issue_attachments");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("idx_issue_attachments_issue_id");

                    b.HasIndex("UploadedByAccountId")
                        .HasDatabaseName("idx_issue_attachments_uploaded_by_account_id");

                    b.HasIndex("IssueId", "IsDeleted")
                        .HasDatabaseName("idx_issue_attachments_issue_deleted");

                    b.ToTable("issue_attachments", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.IssuePriority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_issue_priorities");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_issue_priorities_code");

                    b.ToTable("issue_priorities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1cc8b25d-a2e8-40d2-b971-5193ffbf2fe3"),
                            Code = "low",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "低優先級。",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Low",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("dc8a3357-7002-46f8-98c8-ad46476d7515"),
                            Code = "medium",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "一般預設優先級。",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Medium",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3e722449-95fd-4793-a3c1-8437acd5d5e4"),
                            Code = "high",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "高優先級。",
                            IsActive = true,
                            IsSystem = true,
                            Name = "High",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("8178b599-48da-4743-a560-d3633477f1ac"),
                            Code = "critical",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "需要立即關注的關鍵優先級。",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Critical",
                            SortOrder = 4,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.IssueRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_account_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("RelationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("relation_type_id");

                    b.Property<Guid>("SourceIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_issue_id");

                    b.Property<Guid>("TargetIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_issue_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_issue_relations");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("DeletedByAccountId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_issue_relations_project");

                    b.HasIndex("TargetIssueId")
                        .IsUnique()
                        .HasDatabaseName("uq_issue_relations_active_parent")
                        .HasFilter("is_deleted = false AND relation_type_id = '9fe7e36b-a461-4bfa-8ba8-3e5d201184c2'");

                    b.HasIndex("UpdatedByAccountId");

                    b.HasIndex("SourceIssueId", "IsDeleted")
                        .HasDatabaseName("idx_issue_relations_source_active");

                    b.HasIndex("TargetIssueId", "IsDeleted")
                        .HasDatabaseName("idx_issue_relations_target_active");

                    b.HasIndex("RelationTypeId", "SourceIssueId", "TargetIssueId")
                        .IsUnique()
                        .HasDatabaseName("uq_issue_relations_active")
                        .HasFilter("is_deleted = false");

                    b.ToTable("issue_relations", null, t =>
                        {
                            t.HasCheckConstraint("ck_issue_relations_deleted_metadata", "(is_deleted = false AND deleted_at IS NULL AND deleted_by_account_id IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND deleted_by_account_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_issue_relations_distinct_issues", "source_issue_id <> target_issue_id");
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.IssueRelationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("DirectionKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("direction_kind");

                    b.Property<string>("ForwardLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("forward_label");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("ReverseLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reverse_label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_issue_relation_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_issue_relation_types_code");

                    b.ToTable("issue_relation_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f01d4ad-70e3-4c7f-9b7c-27f5d32001a1"),
                            Code = "related",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DirectionKind = "symmetric",
                            ForwardLabel = "Relates to",
                            IsActive = true,
                            IsSystem = true,
                            ReverseLabel = "Relates to",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("9fe7e36b-a461-4bfa-8ba8-3e5d201184c2"),
                            Code = "parent_of",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DirectionKind = "hierarchical",
                            ForwardLabel = "Parent of",
                            IsActive = true,
                            IsSystem = true,
                            ReverseLabel = "Child of",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("04fd64b0-e17c-41a4-9907-d36dc630b377"),
                            Code = "blocks",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DirectionKind = "directed",
                            ForwardLabel = "Blocks",
                            IsActive = true,
                            IsSystem = true,
                            ReverseLabel = "Blocked by",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5be46e72-6c93-4766-8599-31e90ed45248"),
                            Code = "duplicates",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DirectionKind = "directed",
                            ForwardLabel = "Duplicates",
                            IsActive = true,
                            IsSystem = true,
                            ReverseLabel = "Duplicated by",
                            SortOrder = 4,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c8d1fd1f-3528-4b20-bb6e-febda1adcb71"),
                            Code = "tests",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DirectionKind = "directed",
                            ForwardLabel = "Tests / verifies",
                            IsActive = true,
                            IsSystem = true,
                            ReverseLabel = "Tested / verified by",
                            SortOrder = 5,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.IssueStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_issue_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_issue_statuses_code");

                    b.ToTable("issue_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b211fd1-20f5-4bcb-a3f2-2bb222472c10"),
                            Category = "todo",
                            Code = "created",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "表示任務已建立，尚未正式進入處理。",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Created",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("343e8e3c-4baa-41a3-bd3e-7840ae938244"),
                            Category = "doing",
                            Code = "in_progress",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "表示任務目前正在處理中。",
                            IsActive = true,
                            IsSystem = true,
                            Name = "In Progress",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b48dfc2c-1084-45ff-8c93-ac7d9613943b"),
                            Category = "doing",
                            Code = "verifying",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "表示任務目前正在驗證中。",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Verifying",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("62059722-9c39-4bce-b805-2490cdb6fe77"),
                            Category = "done",
                            Code = "completed",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "表示任務已完成。",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Completed",
                            SortOrder = 4,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.IssueType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_issue_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_issue_types_code");

                    b.ToTable("issue_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("28395b03-a812-4e53-bbde-85a598166d71"),
                            Code = "story",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "用來表示具體需求或使用者價值。",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Story",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d179951d-a8b4-4a37-8059-e79dc8ea25fb"),
                            Code = "task",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "用來表示一般執行工作項目。",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Task",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("66f5813f-a357-47de-961a-572744bc25a9"),
                            Code = "bug",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "用來表示缺陷或異常問題。",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Bug",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7c80596d-325c-43c1-9e1b-757b14f975e8"),
                            Code = "spike",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "用來表示研究、驗證或技術探索工作。",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Spike",
                            SortOrder = 4,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_projects_code");

                    b.HasIndex("CreatedByAccountId")
                        .HasDatabaseName("idx_projects_created_by_account_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.ProjectAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_project_audit_events");

                    b.HasIndex("ActorId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_project_audit_events_occurred_at");

                    b.ToTable("project_audit_events", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_project_members");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_project_members_account_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_project_members_project_id");

                    b.HasIndex("ProjectId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("uq_project_members_active_member")
                        .HasFilter("status = 'active'");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("idx_project_members_project_status");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.ProjectMemberRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<Guid>("ProjectMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_member_id");

                    b.Property<Guid>("ProjectRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_project_member_roles");

                    b.HasIndex("ProjectMemberId")
                        .HasDatabaseName("idx_project_member_roles_project_member_id");

                    b.HasIndex("ProjectRoleId")
                        .HasDatabaseName("idx_project_member_roles_project_role_id");

                    b.HasIndex("ProjectMemberId", "ProjectRoleId")
                        .IsUnique()
                        .HasDatabaseName("uq_project_member_roles_member_role");

                    b.ToTable("project_member_roles", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.ProjectRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_project_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_project_roles_code");

                    b.ToTable("project_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            Code = "owner",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "專案擁有者",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Owner",
                            SortOrder = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            Code = "manager",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "專案管理者",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Manager",
                            SortOrder = 2,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ead22957-af22-47eb-a7de-782145087141"),
                            Code = "contributor",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "專案參與者",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Contributor",
                            SortOrder = 3,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c5684ccd-30b0-43aa-85ef-7f1c23835492"),
                            Code = "reviewer",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "專案審查者",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Reviewer",
                            SortOrder = 4,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.ProjectRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<Guid>("ProjectRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_project_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("idx_project_role_permissions_permission_id");

                    b.HasIndex("ProjectRoleId")
                        .HasDatabaseName("idx_project_role_permissions_project_role_id");

                    b.HasIndex("ProjectRoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("uq_project_role_permissions_role_permission");

                    b.ToTable("project_role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("96c506cf-9f94-c7f0-8b37-fb5e36d3c942"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("1e42b09d-9839-4e8c-951c-38c941f9e4ca"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("09d1f8f6-e79f-2549-4831-57b5a466b4c4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("f622c88d-d0f0-40ed-86c0-bba2c3ff44c9"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5b915700-ab90-4cd7-5be9-6ee4170dc5b5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("23cffaf6-9d01-4116-9a79-a4970bc01eae"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("deb893dd-4005-6b3e-cce7-273101e44b58"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("bb8afb36-8753-4383-bce7-83065a92c0d3"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ff720db8-68d9-f312-14d8-e48eb43a11d4"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("0cc976a0-4f5a-4ce4-9309-6f4476522aa6"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7d3e0fb5-621d-7b7b-e25b-5e5b6071536c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("3c2bdd52-7445-4a16-9750-1b28d97bf109"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("cc648413-32df-b9ce-6d4f-15b5338e85c7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("3ed83136-9532-4e6e-8adb-b73ae9863a2c"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("c1ab8a31-12ad-ae37-f6f6-f4ebd9388803"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("a5fa36de-f8eb-491a-981c-f2f17244fa2b"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ab7c0798-0b76-41fd-2347-fa7098996c4c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("084b565e-e59c-4b48-9a4d-2de2a58e0a9d"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7bd83598-3fbc-cfee-018f-ce06caa5557f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("60098112-f880-40d8-97d6-bed5784f83a0"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("385b399f-53a5-3276-7af4-50f7a5f51094"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("2f36b9f4-b7f1-4cd2-af25-46393d560b13"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("66274a3a-f0c7-2ccc-0464-9477bb2eb2f1"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("081eced1-97b4-4f3e-bb05-56cc3053de6f"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4cccee23-9e2f-95c9-c31d-c907cb5be262"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("bce4a59e-47d6-4664-bda4-c1ea66b50ec1"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("288b0347-ad68-8719-c2d1-994aa373b7cd"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("811e7203-b5ab-4b2c-83aa-8e071f68b36f"),
                            ProjectRoleId = new Guid("4f5961ac-5a4b-49e1-a73c-451d43a39718"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7e0b87b3-8e88-a35b-0f7e-cefc0668cd79"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("1e42b09d-9839-4e8c-951c-38c941f9e4ca"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("30a8a773-c19c-bbdb-209e-f6f8db9cf14e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("f622c88d-d0f0-40ed-86c0-bba2c3ff44c9"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("3ffe1b27-a34a-df3f-2dbb-0b6c5f3590f2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("23cffaf6-9d01-4116-9a79-a4970bc01eae"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("2604dda8-60ba-05de-d32e-c2dbd8d76bdf"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("bb8afb36-8753-4383-bce7-83065a92c0d3"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("ad5b3190-abee-b56b-cdf2-33da880f5c0d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("0cc976a0-4f5a-4ce4-9309-6f4476522aa6"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5521f42d-10ad-a57a-2a6a-27580593012e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("3c2bdd52-7445-4a16-9750-1b28d97bf109"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("4c1e77da-615a-901c-3ff4-4d7f087cceb2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("3ed83136-9532-4e6e-8adb-b73ae9863a2c"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("99b841b8-6726-5ae3-696b-5627dc4ba212"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("a5fa36de-f8eb-491a-981c-f2f17244fa2b"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("06a0d3a1-6481-bacc-bf1c-aee267417d30"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("084b565e-e59c-4b48-9a4d-2de2a58e0a9d"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("86141116-7282-5a53-7909-22b3f100fb42"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("60098112-f880-40d8-97d6-bed5784f83a0"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("bb483fe6-2bfd-cf0c-96d3-249f659a0bea"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("2f36b9f4-b7f1-4cd2-af25-46393d560b13"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("51894281-7d9b-8c4c-a6b2-caa5d4b4b572"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("081eced1-97b4-4f3e-bb05-56cc3053de6f"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6ce13b9e-40e6-714e-a06e-3e9d5ca6ba57"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("bce4a59e-47d6-4664-bda4-c1ea66b50ec1"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("13deec66-f65a-27c8-0bb7-6ba91139d72f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("811e7203-b5ab-4b2c-83aa-8e071f68b36f"),
                            ProjectRoleId = new Guid("836e894f-ca1d-4fd9-af14-b987882400dd"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("93e8919c-4290-a88f-691f-79561e047706"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("1e42b09d-9839-4e8c-951c-38c941f9e4ca"),
                            ProjectRoleId = new Guid("ead22957-af22-47eb-a7de-782145087141"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("d7731f17-381a-1370-3cad-5bb18f577f51"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("3c2bdd52-7445-4a16-9750-1b28d97bf109"),
                            ProjectRoleId = new Guid("ead22957-af22-47eb-a7de-782145087141"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("faf62a01-0652-7193-e98d-610e1534037e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("3ed83136-9532-4e6e-8adb-b73ae9863a2c"),
                            ProjectRoleId = new Guid("ead22957-af22-47eb-a7de-782145087141"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("92f69bdd-ef64-70c9-0b80-d0f0e20b113f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("a5fa36de-f8eb-491a-981c-f2f17244fa2b"),
                            ProjectRoleId = new Guid("ead22957-af22-47eb-a7de-782145087141"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("7492771b-b822-715a-42f4-c9037f8e470e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("084b565e-e59c-4b48-9a4d-2de2a58e0a9d"),
                            ProjectRoleId = new Guid("ead22957-af22-47eb-a7de-782145087141"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5664acb8-a42e-bf85-3b01-87392c6af413"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("60098112-f880-40d8-97d6-bed5784f83a0"),
                            ProjectRoleId = new Guid("ead22957-af22-47eb-a7de-782145087141"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("5d43c4cc-275e-37d2-2aee-2b334478cdec"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("2f36b9f4-b7f1-4cd2-af25-46393d560b13"),
                            ProjectRoleId = new Guid("ead22957-af22-47eb-a7de-782145087141"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("bb795ad9-8d86-b5d1-c5c9-ff5a8b85377b"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("081eced1-97b4-4f3e-bb05-56cc3053de6f"),
                            ProjectRoleId = new Guid("ead22957-af22-47eb-a7de-782145087141"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("24db33d8-ef7f-b4d8-430c-cbbeecdf7f0f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("bce4a59e-47d6-4664-bda4-c1ea66b50ec1"),
                            ProjectRoleId = new Guid("ead22957-af22-47eb-a7de-782145087141"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("eb2537bb-c144-5722-3327-ce1fa43ea265"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("1e42b09d-9839-4e8c-951c-38c941f9e4ca"),
                            ProjectRoleId = new Guid("c5684ccd-30b0-43aa-85ef-7f1c23835492"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f25f7d44-4184-8932-7b42-269884b8ce8f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("3ed83136-9532-4e6e-8adb-b73ae9863a2c"),
                            ProjectRoleId = new Guid("c5684ccd-30b0-43aa-85ef-7f1c23835492"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("b71a6531-a4ad-830f-fa2b-fe76b71663f6"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("084b565e-e59c-4b48-9a4d-2de2a58e0a9d"),
                            ProjectRoleId = new Guid("c5684ccd-30b0-43aa-85ef-7f1c23835492"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("f6cf006e-4182-6ea6-219a-5bb2b6627857"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("60098112-f880-40d8-97d6-bed5784f83a0"),
                            ProjectRoleId = new Guid("c5684ccd-30b0-43aa-85ef-7f1c23835492"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("21ef0d84-116e-fdf9-2dd5-acfdfd36f1a3"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("2f36b9f4-b7f1-4cd2-af25-46393d560b13"),
                            ProjectRoleId = new Guid("c5684ccd-30b0-43aa-85ef-7f1c23835492"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("33e94581-847a-d7f3-704d-f90bba5fc295"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("bce4a59e-47d6-4664-bda4-c1ea66b50ec1"),
                            ProjectRoleId = new Guid("c5684ccd-30b0-43aa-85ef-7f1c23835492"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Infrastructure.AccountReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("accounts", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Infrastructure.PermissionReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.Issue", b =>
                {
                    b.HasOne("KhaiKang.Modules.ProjectManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("AssigneeAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_issues_assignee_account");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.IssuePriority", "IssuePriority")
                        .WithMany()
                        .HasForeignKey("IssuePriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issues_issue_priority");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.IssueStatus", "IssueStatus")
                        .WithMany()
                        .HasForeignKey("IssueStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issues_issue_status");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.IssueType", "IssueType")
                        .WithMany()
                        .HasForeignKey("IssueTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issues_issue_type");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_project");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("ReporterAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issues_reporter_account");

                    b.Navigation("IssuePriority");

                    b.Navigation("IssueStatus");

                    b.Navigation("IssueType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.IssueAttachment", b =>
                {
                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attachments_issue");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("UploadedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attachments_uploaded_by_account");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.IssueRelation", b =>
                {
                    b.HasOne("KhaiKang.Modules.ProjectManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_issue_relations_created_by_account");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("DeletedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_issue_relations_deleted_by_account");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_relations_project");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.IssueRelationType", "RelationType")
                        .WithMany()
                        .HasForeignKey("RelationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issue_relations_type");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.Issue", "SourceIssue")
                        .WithMany()
                        .HasForeignKey("SourceIssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issue_relations_source_issue");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.Issue", "TargetIssue")
                        .WithMany()
                        .HasForeignKey("TargetIssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_issue_relations_target_issue");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_issue_relations_updated_by_account");

                    b.Navigation("Project");

                    b.Navigation("RelationType");

                    b.Navigation("SourceIssue");

                    b.Navigation("TargetIssue");
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.Project", b =>
                {
                    b.HasOne("KhaiKang.Modules.ProjectManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_created_by_account");
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.ProjectAuditEvent", b =>
                {
                    b.HasOne("KhaiKang.Modules.ProjectManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_audit_events_actor");
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.ProjectMember", b =>
                {
                    b.HasOne("KhaiKang.Modules.ProjectManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_account");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_members_project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.ProjectMemberRole", b =>
                {
                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.ProjectMember", "ProjectMember")
                        .WithMany("Roles")
                        .HasForeignKey("ProjectMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_member_roles_member");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.ProjectRole", "ProjectRole")
                        .WithMany()
                        .HasForeignKey("ProjectRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_member_roles_role");

                    b.Navigation("ProjectMember");

                    b.Navigation("ProjectRole");
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.ProjectRolePermission", b =>
                {
                    b.HasOne("KhaiKang.Modules.ProjectManagement.Infrastructure.PermissionReference", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_role_permissions_permission");

                    b.HasOne("KhaiKang.Modules.ProjectManagement.Domain.ProjectRole", "ProjectRole")
                        .WithMany("Permissions")
                        .HasForeignKey("ProjectRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_role_permissions_role");

                    b.Navigation("Permission");

                    b.Navigation("ProjectRole");
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.Project", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.ProjectMember", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("KhaiKang.Modules.ProjectManagement.Domain.ProjectRole", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
