// <auto-generated />
using System;
using KhaiKang.Modules.TestManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KhaiKang.Modules.TestManagement.Infrastructure.Migrations
{
    [DbContext(typeof(TestManagementDbContext))]
    [Migration("20260811002904_AddIssueTestTraceability")]
    partial class AddIssueTestTraceability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CaseNo")
                        .HasColumnType("integer")
                        .HasColumnName("case_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("OverallExpectedResult")
                        .HasColumnType("text")
                        .HasColumnName("overall_expected_result");

                    b.Property<string>("Preconditions")
                        .HasColumnType("text")
                        .HasColumnName("preconditions");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_suite_id");

                    b.Property<Guid>("TestWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_workspace_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_cases");

                    b.HasIndex("TestSuiteId")
                        .HasDatabaseName("idx_test_cases_test_suite_id");

                    b.HasIndex("TestSuiteId", "SortOrder")
                        .HasDatabaseName("idx_test_cases_test_suite_sort_order");

                    b.HasIndex("TestSuiteId", "Status")
                        .HasDatabaseName("idx_test_cases_test_suite_status");

                    b.HasIndex("TestWorkspaceId", "CaseNo")
                        .IsUnique()
                        .HasDatabaseName("uq_test_cases_workspace_case_no");

                    b.ToTable("test_cases", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestCaseAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("storage_provider");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<Guid>("UploadedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_case_attachments");

                    b.HasIndex("UploadedByAccountId");

                    b.HasIndex("TestCaseId", "IsDeleted")
                        .HasDatabaseName("idx_test_case_attachments_case_deleted");

                    b.ToTable("test_case_attachments", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestCaseRequirementLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_account_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("RequirementIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_issue_id");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<Guid>("TestWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_workspace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_case_requirement_links");

                    b.HasIndex("DeletedByAccountId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RequirementIssueId", "IsDeleted")
                        .HasDatabaseName("idx_test_case_requirement_links_issue_active");

                    b.HasIndex("TestCaseId", "RequirementIssueId")
                        .IsUnique()
                        .HasDatabaseName("uq_test_case_requirement_links_active")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("TestWorkspaceId", "ProjectId", "IsDeleted")
                        .HasDatabaseName("idx_test_case_requirement_links_workspace_project_active");

                    b.ToTable("test_case_requirement_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_test_case_requirement_links_deleted_metadata", "(is_deleted = false AND deleted_at IS NULL AND deleted_by_account_id IS NULL) OR (is_deleted = true AND deleted_at IS NOT NULL AND deleted_by_account_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestCaseTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<Guid>("TestTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_tag_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_case_tags");

                    b.HasIndex("TestCaseId")
                        .HasDatabaseName("idx_test_case_tags_test_case_id");

                    b.HasIndex("TestTagId")
                        .HasDatabaseName("idx_test_case_tags_test_tag_id");

                    b.HasIndex("TestCaseId", "TestTagId")
                        .IsUnique()
                        .HasDatabaseName("uq_test_case_tags_case_tag");

                    b.ToTable("test_case_tags", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PlanNo")
                        .HasColumnType("integer")
                        .HasColumnName("plan_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TestIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_issue_id");

                    b.Property<Guid?>("TestIssueProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_issue_project_id");

                    b.Property<Guid>("TestWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_workspace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_plans");

                    b.HasIndex("TestIssueId");

                    b.HasIndex("TestIssueProjectId");

                    b.HasIndex("TestWorkspaceId", "PlanNo")
                        .IsUnique()
                        .HasDatabaseName("uq_test_plans_workspace_plan_no");

                    b.HasIndex("TestWorkspaceId", "Status")
                        .HasDatabaseName("idx_test_plans_workspace_status");

                    b.ToTable("test_plans", null, t =>
                        {
                            t.HasCheckConstraint("ck_test_plans_test_issue_pair", "(test_issue_project_id IS NULL AND test_issue_id IS NULL) OR (test_issue_project_id IS NOT NULL AND test_issue_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<Guid>("TestPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_plan_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_plan_items");

                    b.HasIndex("TestCaseId");

                    b.HasIndex("TestPlanId", "SortOrder")
                        .HasDatabaseName("idx_test_plan_items_plan_sort_order");

                    b.HasIndex("TestPlanId", "TestCaseId")
                        .IsUnique()
                        .HasDatabaseName("uq_test_plan_items_plan_case");

                    b.ToTable("test_plan_items", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RunNo")
                        .HasColumnType("integer")
                        .HasColumnName("run_no");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("StartedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("started_by_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid?>("TestIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_issue_id");

                    b.Property<Guid?>("TestIssueProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_issue_project_id");

                    b.Property<Guid>("TestPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_plan_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_runs");

                    b.HasIndex("StartedByAccountId");

                    b.HasIndex("TestIssueId");

                    b.HasIndex("TestIssueProjectId");

                    b.HasIndex("TestPlanId", "RunNo")
                        .IsUnique()
                        .HasDatabaseName("uq_test_runs_plan_run_no");

                    b.HasIndex("TestPlanId", "Status")
                        .HasDatabaseName("idx_test_runs_plan_status");

                    b.ToTable("test_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_test_runs_test_issue_pair", "(test_issue_project_id IS NULL AND test_issue_id IS NULL) OR (test_issue_project_id IS NOT NULL AND test_issue_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestRunBugLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BugIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("bug_issue_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TestRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_run_id");

                    b.Property<Guid>("TestWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_workspace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_run_bug_links");

                    b.HasIndex("BugIssueId")
                        .IsUnique()
                        .HasDatabaseName("uq_test_run_bug_links_bug_issue");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TestRunId")
                        .HasDatabaseName("idx_test_run_bug_links_run");

                    b.HasIndex("TestWorkspaceId", "ProjectId")
                        .HasDatabaseName("idx_test_run_bug_links_workspace_project");

                    b.ToTable("test_run_bug_links", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestRunItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActualResult")
                        .HasColumnType("text")
                        .HasColumnName("actual_result");

                    b.Property<string>("CaseDescription")
                        .HasColumnType("text")
                        .HasColumnName("case_description");

                    b.Property<string>("CaseTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("case_title");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<Guid?>("ExecutedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("executed_by_account_id");

                    b.Property<string>("OverallExpectedResult")
                        .HasColumnType("text")
                        .HasColumnName("overall_expected_result");

                    b.Property<string>("Preconditions")
                        .HasColumnType("text")
                        .HasColumnName("preconditions");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result_status");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<Guid>("TestRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_run_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_run_items");

                    b.HasIndex("ExecutedByAccountId");

                    b.HasIndex("TestCaseId");

                    b.HasIndex("TestRunId", "SortOrder")
                        .HasDatabaseName("idx_test_run_items_run_sort_order");

                    b.ToTable("test_run_items", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestRunItemAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("file_hash");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("storage_provider");

                    b.Property<Guid>("TestRunItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_run_item_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<Guid>("UploadedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_run_item_attachments");

                    b.HasIndex("UploadedByAccountId");

                    b.HasIndex("TestRunItemId", "IsDeleted")
                        .HasDatabaseName("idx_test_run_item_attachments_item_deleted");

                    b.ToTable("test_run_item_attachments", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestRunItemStepResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActualResult")
                        .HasColumnType("text")
                        .HasColumnName("actual_result");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<DateTimeOffset?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<Guid?>("ExecutedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("executed_by_account_id");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_result");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result_status");

                    b.Property<int>("StepNo")
                        .HasColumnType("integer")
                        .HasColumnName("step_no");

                    b.Property<Guid>("TestRunItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_run_item_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_run_item_step_results");

                    b.HasIndex("ExecutedByAccountId");

                    b.HasIndex("TestRunItemId", "StepNo")
                        .IsUnique()
                        .HasDatabaseName("uq_test_run_item_steps_item_step_no");

                    b.ToTable("test_run_item_step_results", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_result");

                    b.Property<int>("StepNo")
                        .HasColumnType("integer")
                        .HasColumnName("step_no");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_case_steps");

                    b.HasIndex("TestCaseId")
                        .HasDatabaseName("idx_test_case_steps_test_case_id");

                    b.HasIndex("TestCaseId", "StepNo")
                        .IsUnique()
                        .HasDatabaseName("uq_test_case_steps_case_step_no");

                    b.ToTable("test_case_steps", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TestWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_workspace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_suites");

                    b.HasIndex("ParentId");

                    b.HasIndex("TestWorkspaceId", "ParentId", "SortOrder")
                        .HasDatabaseName("idx_test_suites_workspace_parent_sort_order");

                    b.ToTable("test_suites", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_test_tags_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_test_tags_status");

                    b.ToTable("test_tags", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefix");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_workspaces");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_test_workspaces_name");

                    b.HasIndex("Prefix")
                        .IsUnique()
                        .HasDatabaseName("uq_test_workspaces_prefix");

                    b.ToTable("test_workspaces", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestWorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TestWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_workspace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_workspace_members");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_test_workspace_members_account_id");

                    b.HasIndex("TestWorkspaceId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("uq_test_workspace_members_workspace_account");

                    b.HasIndex("TestWorkspaceId", "Status")
                        .HasDatabaseName("idx_test_workspace_members_workspace_status");

                    b.ToTable("test_workspace_members", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestWorkspaceProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TestWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_workspace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_workspace_projects");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_test_workspace_projects_project_id");

                    b.HasIndex("TestWorkspaceId", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("uq_test_workspace_projects_workspace_project");

                    b.ToTable("test_workspace_projects", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Infrastructure.AccountReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("accounts", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Infrastructure.IssueReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("issues", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Infrastructure.ProjectReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("projects", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestCase", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestSuite", "Suite")
                        .WithMany()
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_cases_test_suite");

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestCaseAttachment", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_attachments_case");

                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("UploadedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_attachments_uploaded_by_account");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestCaseRequirementLink", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("DeletedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_case_requirement_links_deleted_by_account");

                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.ProjectReference", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_requirement_links_project");

                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.IssueReference", null)
                        .WithMany()
                        .HasForeignKey("RequirementIssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_requirement_links_issue");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_requirement_links_case");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestWorkspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("TestWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_requirement_links_workspace");

                    b.Navigation("TestCase");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestCaseTag", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestCase", "TestCase")
                        .WithMany("Tags")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_tags_case");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestTag", "Tag")
                        .WithMany("Cases")
                        .HasForeignKey("TestTagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_tags_tag");

                    b.Navigation("Tag");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestPlan", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.IssueReference", null)
                        .WithMany()
                        .HasForeignKey("TestIssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_plans_test_issue");

                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.ProjectReference", null)
                        .WithMany()
                        .HasForeignKey("TestIssueProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_plans_test_issue_project");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestWorkspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("TestWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_plans_workspace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestPlanItem", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_plan_items_case");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestPlan", null)
                        .WithMany("Items")
                        .HasForeignKey("TestPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_plan_items_plan");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestRun", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("StartedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_runs_started_by_account");

                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.IssueReference", null)
                        .WithMany()
                        .HasForeignKey("TestIssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_runs_test_issue");

                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.ProjectReference", null)
                        .WithMany()
                        .HasForeignKey("TestIssueProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_runs_test_issue_project");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("TestPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_runs_plan");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestRunBugLink", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.IssueReference", null)
                        .WithMany()
                        .HasForeignKey("BugIssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_run_bug_links_issue");

                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.ProjectReference", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_run_bug_links_project");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestRun", "TestRun")
                        .WithMany()
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_run_bug_links_run");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestWorkspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("TestWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_run_bug_links_workspace");

                    b.Navigation("TestRun");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestRunItem", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("ExecutedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_run_items_executed_by_account");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestCase", null)
                        .WithMany()
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_run_items_case");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestRun", null)
                        .WithMany("Items")
                        .HasForeignKey("TestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_run_items_run");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestRunItemAttachment", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestRunItem", "TestRunItem")
                        .WithMany()
                        .HasForeignKey("TestRunItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_run_item_attachments_item");

                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("UploadedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_run_item_attachments_uploaded_by_account");

                    b.Navigation("TestRunItem");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestRunItemStepResult", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("ExecutedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_run_item_steps_executed_by_account");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestRunItem", null)
                        .WithMany("Steps")
                        .HasForeignKey("TestRunItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_run_item_steps_run_item");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestStep", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestCase", "TestCase")
                        .WithMany("Steps")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_steps_test_case");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestSuite", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestSuite", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_suites_parent");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestWorkspace", "Workspace")
                        .WithMany("Suites")
                        .HasForeignKey("TestWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_suites_workspace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestWorkspaceMember", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_workspace_members_account");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestWorkspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("TestWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_workspace_members_workspace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestWorkspaceProject", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.ProjectReference", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_workspace_projects_project");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestWorkspace", "Workspace")
                        .WithMany("Projects")
                        .HasForeignKey("TestWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_workspace_projects_workspace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestCase", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestRun", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestRunItem", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestTag", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestWorkspace", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Projects");

                    b.Navigation("Suites");
                });
#pragma warning restore 612, 618
        }
    }
}
