// <auto-generated />
using System;
using KhaiKang.Modules.TestManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KhaiKang.Modules.TestManagement.Infrastructure.Migrations
{
    [DbContext(typeof(TestManagementDbContext))]
    partial class TestManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("OverallExpectedResult")
                        .HasColumnType("text")
                        .HasColumnName("overall_expected_result");

                    b.Property<string>("Preconditions")
                        .HasColumnType("text")
                        .HasColumnName("preconditions");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_suite_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_cases");

                    b.HasIndex("TestSuiteId")
                        .HasDatabaseName("idx_test_cases_test_suite_id");

                    b.HasIndex("TestSuiteId", "SortOrder")
                        .HasDatabaseName("idx_test_cases_test_suite_sort_order");

                    b.HasIndex("TestSuiteId", "Status")
                        .HasDatabaseName("idx_test_cases_test_suite_status");

                    b.ToTable("test_cases", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expected_result");

                    b.Property<int>("StepNo")
                        .HasColumnType("integer")
                        .HasColumnName("step_no");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_case_steps");

                    b.HasIndex("TestCaseId")
                        .HasDatabaseName("idx_test_case_steps_test_case_id");

                    b.HasIndex("TestCaseId", "StepNo")
                        .IsUnique()
                        .HasDatabaseName("uq_test_case_steps_case_step_no");

                    b.ToTable("test_case_steps", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TestWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_workspace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_suites");

                    b.HasIndex("ParentId");

                    b.HasIndex("TestWorkspaceId", "ParentId", "SortOrder")
                        .HasDatabaseName("idx_test_suites_workspace_parent_sort_order");

                    b.ToTable("test_suites", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestWorkspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefix");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_workspaces");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_test_workspaces_name");

                    b.HasIndex("Prefix")
                        .IsUnique()
                        .HasDatabaseName("uq_test_workspaces_prefix");

                    b.ToTable("test_workspaces", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestWorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_account_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TestWorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_workspace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_account_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_test_workspace_members");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_test_workspace_members_account_id");

                    b.HasIndex("TestWorkspaceId", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("uq_test_workspace_members_workspace_account");

                    b.HasIndex("TestWorkspaceId", "Status")
                        .HasDatabaseName("idx_test_workspace_members_workspace_status");

                    b.ToTable("test_workspace_members", (string)null);
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Infrastructure.AccountReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("accounts", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestCase", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestSuite", "Suite")
                        .WithMany()
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_cases_test_suite");

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestStep", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestCase", "TestCase")
                        .WithMany("Steps")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_case_steps_test_case");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestSuite", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestSuite", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_suites_parent");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestWorkspace", "Workspace")
                        .WithMany("Suites")
                        .HasForeignKey("TestWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_suites_workspace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestWorkspaceMember", b =>
                {
                    b.HasOne("KhaiKang.Modules.TestManagement.Infrastructure.AccountReference", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_workspace_members_account");

                    b.HasOne("KhaiKang.Modules.TestManagement.Domain.TestWorkspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("TestWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_workspace_members_workspace");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestCase", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("KhaiKang.Modules.TestManagement.Domain.TestWorkspace", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Suites");
                });
#pragma warning restore 612, 618
        }
    }
}
