<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\common\KhaiKang.CommonUtils\KhaiKang.CommonUtils.csproj" />
    <ProjectReference Include="..\..\common\KhaiKang.CommonUtils.Web\KhaiKang.CommonUtils.Web.csproj" />
    <ProjectReference Include="..\KhaiKang.Modules.Identity\KhaiKang.Modules.Identity.csproj" />
  </ItemGroup>
</Project>
